# Generated by Django 2.0.7 on 2018-09-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=250)),
                ('lastName', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('studentId', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TutoringSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorName', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('tutorPicture', models.CharField(max_length=1000)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
