# Generated by Django 2.0.7 on 2018-09-14 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=25, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
